services :
  redis:
    image: redis:7-alpine
    container_name: redis_learning
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_learning_data:/data
    
  mongo:
    image: mongo:7
    container_name: mongo_learning
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: redis_learning
    volumes:
      - mongo_learning_data:/data/db

volumes:
  redis_learning_data:
  mongo_learning_data: